# ckpt_path: /home/btang5/work/2025/geometric-aware-diffusion/logs/autoencoder/lightning_logs/version_0/checkpoints/epoch=32-step=12903.ckpt
trainer:
  max_epochs: 100
  default_root_dir: logs/autoencoder_linear_advanced # Name of the experiments
  devices: 4
  strategy: ddp
model: 
  class_path: module.autoencoder_module.AutoEncoderModule
  init_args:
    autoencoder: 
      class_path: model.autoencoder_linear.AdvancedAutoencoder
data:
  class_path: dataset.cifar10.Cifar10DataModule
  init_args:
    batch_size: 128
  